// Generated by tools/gen_longform_ios.py -- do not edit by hand.
//
// Every block here is an exact size, chosen to sit just under or just over one of
// the plugin's thresholds. The filler never opens a brace, so the sizes are what
// the generator says they are and nothing else is counted.

import Foundation

protocol Fetching {
    func fetch() -> Int
}

struct UnderLabel {
    func short() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        return total
    }

    func justUnder() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        return total
    }

    private var pad0 = 0
    private var pad1 = 1
    private var pad2 = 2
    private var pad3 = 3
    private var pad4 = 4
    private var pad5 = 5
}

struct OverLabel {
    func justOver() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        return total
    }

    func tiny() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        return total
    }

    private var pad0 = 0
    private var pad1 = 1
    private var pad2 = 2
    private var pad3 = 3
    private var pad4 = 4
    private var pad5 = 5
}

final class UnderSpan {
    init(seed: Int) {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        return total
    }

    deinit {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        return total
    }

    func justUnderSpan() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        return total
    }

    private var pad0 = 0
    private var pad1 = 1
    private var pad2 = 2
    private var pad3 = 3
    private var pad4 = 4
    private var pad5 = 5
    private var pad6 = 6
    private var pad7 = 7
    private var pad8 = 8
    private var pad9 = 9
    private var pad10 = 10
    private var pad11 = 11
    private var pad12 = 12
    private var pad13 = 13
    private var pad14 = 14
    private var pad15 = 15
}

final class OverSpan {
    func overSpan() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        return total
    }

    var underPropertySpan: Int {
        get {
            var total = 0
            var index = 0
            var flag = false
            var log = ""
            var values: [Int] = []
            var name = "zoo"
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            name = name.uppercased()
            index = max(index, values.count)
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            name = name.uppercased()
            index = max(index, values.count)
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            return total
        }
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
    }

    var overPropertySpan: Int {
        get {
            var total = 0
            var index = 0
            var flag = false
            var log = ""
            var values: [Int] = []
            var name = "zoo"
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            name = name.uppercased()
            index = max(index, values.count)
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            name = name.uppercased()
            index = max(index, values.count)
            total += index
            log += "step \(index)"
            values.append(index)
            index = index &+ 1
            print(log, total)
            flag = !flag
            name = name.uppercased()
            index = max(index, values.count)
            return total
        }
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
        // padding that opens nothing
    }

    subscript(position: Int) -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        return total
    }

}

actor Counter {
    func bump() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        name = name.uppercased()
        index = max(index, values.count)
        return total
    }

}

extension String: Fetching {
    func fetch() -> Int {
        var total = 0
        var index = 0
        var flag = false
        var log = ""
        var values: [Int] = []
        var name = "zoo"
        total += index
        log += "step \(index)"
        values.append(index)
        index = index &+ 1
        print(log, total)
        flag = !flag
        return total
    }

}

enum Outcome {
    case idle
    case done
}

func withClosures() {
    var total = 0
    let values = [1, 2, 3]

    values.forEach { value in
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
        total += value
    }

    DispatchQueue.main.async {
        total = 0
    }

    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
    total = total &+ 1
}

