// Generated by tools/gen_longform_ios.py -- do not edit by hand.
//
// Objective-C rides on the C++ dialect and adds two shapes of its own; both are
// here at several sizes, around the same thresholds the Swift file straddles.

#import "HTAZoo.h"

@implementation HTAZoo

- (NSInteger)tiny
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    return total;
}

- (NSInteger)justUnderLabel:(NSInteger)index
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    return total;
}

- (NSInteger)justOverLabel:(NSInteger)index andFlag:(BOOL)flag
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    return total;
}

+ (NSInteger)justUnderSpan
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    return total;
}

+ (NSInteger)justOverSpan:(NSString *)name
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    return total;
}

- (void)withBlocks
{
    NSInteger total = 0;

    [UIView animateWithDuration:0.3 animations:^{
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
        total += 1;
    } completion:^(BOOL finished) {
        total = 0;
    }];

    total += 1;
    total += 1;
    total += 1;
    total += 1;
    total += 1;
    total += 1;
    total += 1;
    total += 1;
    (void)total;
}

@end

static NSInteger HTAZooLogEverything(NSArray *items)
{
    NSInteger total = 0;
    NSInteger index = 0;
    BOOL flag = NO;
    NSMutableArray *buffer = [NSMutableArray array];
    NSString *name = @"zoo";
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    name = [name uppercaseString];
    index = MAX(index, (NSInteger)buffer.count);
    total = total * 2 - index;
    total += index;
    index += 1;
    [buffer addObject:@(index)];
    NSLog(@"step %ld", (long)index);
    flag = !flag;
    return total;
}

